name: Dialyzer

on: pull_request

env:
  HOST_NAME: "http://localhost:4000/"

jobs:
  dialyzer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.14]
        otp: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-dialyzer
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp}}-%{{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix depencies
        if: steps.mix-cache-dialyzer.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: ====> dialyzer
        run: mix dialyzer
